# Generated by Django 4.1.1 on 2023-01-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('correo', models.EmailField(max_length=100, verbose_name='Correo')),
                ('proyecto', models.CharField(max_length=200, verbose_name='Nombre del Proyecto')),
                ('mensaje', models.CharField(max_length=500, verbose_name='Mensaje')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Proyecto')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('link_demo', models.URLField(blank=True, null=True, verbose_name='Ver Demo')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='proyectos/%Y/%m/%d', verbose_name='Foto Referencia de Aplicacion')),
            ],
        ),
    ]
