# Generated by Django 4.1.1 on 2023-01-25 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Habilidad')),
                ('nivel', models.CharField(choices=[('basico', 'Basico'), ('avanzado', 'Avanzado'), ('intermedio', 'Intermedio')], default='Basico', max_length=15)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.categoria', verbose_name='Categoria de Habilidad')),
            ],
        ),
    ]
