# Generated by Django 4.1.1 on 2023-01-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('correo', models.EmailField(max_length=300, verbose_name='Correo')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto/%Y/%m/%d', verbose_name='Foto de Perfil')),
                ('lugar_residencia', models.CharField(max_length=50, verbose_name='Lugar de Residencia')),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo que ocupa')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Linkedin')),
                ('telegram', models.URLField(null=True, verbose_name='Telegram')),
                ('whatsaap', models.URLField(null=True, verbose_name='Whatssap')),
                ('github', models.URLField(blank=True, null=True, verbose_name='GitHub')),
                ('anos_trabajo', models.IntegerField(verbose_name='Años de Trabajo')),
                ('proyectos_completados', models.IntegerField(verbose_name='Proyectos Completados')),
                ('clientes_satisfechos', models.IntegerField(verbose_name='Clientes Satisfechos')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/%Y/%m/%d', verbose_name='Curriculum Vitae')),
                ('telefono', models.CharField(max_length=16, null=True, verbose_name='Telefono')),
            ],
        ),
    ]
